services:

  eureka:
    build: ./eureka-server
    container_name: eureka
    restart: always
    ports:
      - "8761:8761"

  config-server:
    build: ./config-server
    container_name: config-server
    restart: always
    ports:
      - "8888:8888"
    depends_on:
      - eureka

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    restart: always
    ports:
      - "9411:9411"

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  auth-service:
    build: ./auth-service
    container_name: auth-service
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - config-server
      - postgres
      - eureka

  delivery-service:
    build: ./delivery-service
    container_name: delivery-service
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - config-server
      - postgres
      - rabbitmq
      - eureka

  tracking-service:
    build: ./tracking-service
    container_name: tracking-service
    restart: always
    ports:
      - "8083:8080"
    depends_on:
      - config-server
      - postgres
      - rabbitmq
      - eureka

  admin-service:
    build: ./admin-service
    container_name: admin-service
    restart: always
    ports:
      - "8084:8080"
    depends_on:
      - config-server
      - postgres
      - rabbitmq
      - eureka

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - eureka
      - auth-service
      - delivery-service
      - tracking-service
      - admin-service

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    restart: always
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/sonarqube
      - SONAR_JDBC_USERNAME=postgres
      - SONAR_JDBC_PASSWORD=root
    depends_on:
      - postgres
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

volumes:
  postgres_data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions: