#spring.application.name=api-gateway
#
#server.port=8080
#
## Eureka
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#eureka.instance.prefer-ip-address=true
#eureka.instance.instance-id=${spring.application.name}:${server.port}
#
## AUTH SERVICE
#spring.cloud.gateway.server.webflux.routes[0].id=auth-service
#spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTH-SERVICE
#spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**
#
## DELIVERY SERVICE
#spring.cloud.gateway.server.webflux.routes[1].id=delivery-service
#spring.cloud.gateway.server.webflux.routes[1].uri=lb://DELIVERY-SERVICE
#spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/deliveries/**
#
#
#spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowedOrigins=*
#spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowedMethods=GET,POST,PUT,DELETE
#spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowedHeaders=*
#
#springdoc.swagger-ui.urls[0].name=Auth Service
#springdoc.swagger-ui.urls[0].url=/auth/v3/api-docs
#springdoc.swagger-ui.urls[1].name=Delivery Service
#springdoc.swagger-ui.urls[1].url=/deliveries/v3/api-docs
#springdoc.swagger-ui.urls[2].name=Tracking Service
#springdoc.swagger-ui.urls[2].url=/tracking/v3/api-docs
#springdoc.swagger-ui.urls[3].name=Admin Service
#springdoc.swagger-ui.urls[3].url=/admin/v3/api-docs
## TRACKING SERVICE
#spring.cloud.gateway.server.webflux.routes[2].id=tracking-service
#spring.cloud.gateway.server.webflux.routes[2].uri=lb://TRACKING-SERVICE
#spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/tracking/**
#
## ADMIN SERVICE
#spring.cloud.gateway.server.webflux.routes[3].id=admin-service
#spring.cloud.gateway.server.webflux.routes[3].uri=lb://ADMIN-SERVICE
#spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/admin/**
#
#spring.main.web-application-type=reactive
#
#springdoc.swagger-ui.path=/swagger-ui.html
#
## Enable tracing
#management.tracing.sampling.probability=1.0
#
## Zipkin server URL
#management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
spring.application.name=api-gateway
spring.config.import=optional:configserver:http://config-server:8888

spring.cloud.config.fail-fast=true
spring.cloud.config.retry.max-attempts=10
spring.cloud.config.retry.initial-interval=2000
spring.cloud.config.retry.max-interval=10000