spring.application.name=eureka-server

server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

logging.level.com.netflix.eureka=DEBUG
logging.level.org.springframework.cloud=DEBUG

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

